name: octavia-diskimage-retrofit
icon: src/icon.svg
adopt-info: retrofit
grade: stable
summary: tool for retrofitting cloud images for use as Octavia Amphora image.
description: |
  tool for retrofitting cloud images for use as Octavia Amphora image.
confinement: devmode
base: core22
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64
  - build-on: ppc64el

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  /usr/share/qemu:
    bind: $SNAP/usr/share/qemu
  /usr/share/seabios:
    bind: $SNAP/usr/share/seabios
  /usr/lib/ipxe:
    bind: $SNAP/usr/lib/ipxe

environment:
  LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
  LIBGUESTFS_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/guestfs/appliance
  TMPDIR: $SNAP_COMMON/tmp
  PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
apps:
  octavia-diskimage-retrofit:
    command: bin/retrofit.sh
    plugs:
      - fuse-support
      - kvm
      - network-bind
parts:
  retrofit:
    plugin: dump
    source: src/retrofit
    override-stage: |
      craftctl default
      craftctl set version=$(git -C $CRAFT_PROJECT_DIR describe --always | sed -e 's/-/+git/;y/-/./' | sed -s 's/^v//')
    organize:
      retrofit.sh: bin/retrofit.sh
  local-elements:
    plugin: dump
    source: src
    organize: 
      elements/*: usr/local/lib/elements/
  octavia-elements:
    plugin: dump
    source: https://opendev.org/openstack/octavia.git
    source-type: git
    source-branch: stable/wallaby
    override-pull: |
      craftctl default
      patch  -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-octavia-elements-amphora-agent-ureadahead.patch
    organize:
      elements/*: usr/local/lib/elements/
  diskimage-builder:
    plugin: python
    source: https://opendev.org/openstack/diskimage-builder.git
    source-type: git
    source-branch: 2.25.0
    override-build: |
      patch -p1 < $CRAFT_PROJECT_DIR/patch/patch-diskimage-builder-manifests-fix-chown.patch
      find diskimage_builder/elements/ -type f -print0 | xargs -0 sed -i '1 s/^#\!.*python$/#\!\/usr\/bin\/env python3/'
      craftctl default
    stage:
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -lib64
  libguestfs:
    after: [diskimage-builder]
    source: https://git.launchpad.net/ubuntu/+source/libguestfs
    source-type: git
    source-tag: ubuntu/jammy
    plugin: autotools
    build-environment:
      - PYTHON: /usr/bin/python3
      - QEMU_CPU: "$(dpkg-architecture -qDEB_HOST_GNU_CPU | sed -r -e 's,i[456]86,i386,' -e 's,sparc.*,sparc64,' -e 's,powerpc(64.*)?,ppc64,' -e 's,arm.*,arm,')"
      - QEMU: /snap/$CRAFT_PROJECT_NAME/current/usr/bin/qemu-system-$QEMU_CPU
    override-build: |
      sed -ie 's/^# deb-src/deb-src/' /etc/apt/sources.list; apt -y update
      apt build-dep -y libguestfs
      mkdir -p /snap/$CRAFT_PROJECT_NAME
      ln -sf $CRAFT_PART_INSTALL /snap/$CRAFT_PROJECT_NAME/current
      dpkg-source --before-build .
      autoreconf
      craftctl default
      rm -f /snap/$CRAFT_PROJECT_NAME/current
      rmdir /snap/$CRAFT_PROJECT_NAME
    override-prime: |
      mkdir -p usr/lib/$CRAFT_ARCH_TRIPLET/guestfs/appliance
      mkdir -p /snap/$CRAFT_PROJECT_NAME
      ln -sf $CRAFT_STAGE /snap/$CRAFT_PROJECT_NAME/current
      env -i LIBGUESTFS_PATH=$CRAFT_STAGE/usr/lib/guestfs LD_LIBRARY_PATH=$CRAFT_STAGE/lib:$CRAFT_STAGE/lib/$CRAFT_ARCH_TRIPLET:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET PATH=$CRAFT_STAGE/usr/sbin:$CRAFT_STAGE/usr/bin:$CRAFT_STAGE/sbin:$CRAFT_STAGE/bin:/usr/sbin:/usr/bin:/sbin:/bin LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1 libguestfs-make-fixed-appliance usr/lib/$CRAFT_ARCH_TRIPLET/guestfs/appliance
      rm -f /snap/$CRAFT_PROJECT_NAME/current
      rmdir /snap/$CRAFT_PROJECT_NAME
      chmod 0644 usr/lib/$CRAFT_ARCH_TRIPLET/guestfs/appliance/kernel
      craftctl default
    autotools-configure-parameters:
      - --disable-silent-rules
      - --disable-gnulib-tests
      - --with-readline
      - --disable-haskell
      - --disable-java
      - --disable-golang
      - --disable-python
      - --disable-perl
      - --disable-php
      - --disable-gobject
      - --disable-lua
      - --disable-erlang
      - --disable-ruby
      - --without-libvirt
      - --prefix=/usr
    build-packages:
      - genisoimage
      - on amd64:
        - linux-image-virtual
        - syslinux
        - extlinux
        - qemu-system-x86
      - on arm64:
        - linux-image-virtual
        - qemu-system-arm
      - on armhf:
        - linux-image-generic
        - qemu-system-arm
      - on i386:
        - linux-image-virtual
        - syslinux
        - extlinux
        - qemu-system-x86
      - on ppc64el:
        - linux-image-virtual
        - qemu-system-ppc
      - on s390x:
        - linux-image-virtual
        - qemu-system-s390x
    stage-packages:
      - genisoimage
      - libmagic1
      - uuid-runtime
      - libjansson4
      - libicu70
      - libxml2
      - ipxe-qemu-256k-compat-efi-roms
      - on amd64:
        - qemu-system-x86
      - on arm64:
        - qemu-system-arm
      - on armhf:
        - qemu-system-arm
      - on i386:
        - qemu-system-x86
      - on ppc64el:
        - qemu-system-ppc
      - on s390x:
        - qemu-system-s390x
      - qemu-utils
      - libslang2
      - libfuse2
      - fuse
  guestfs-tools:
    after: [libguestfs]
    source: https://salsa.debian.org/libvirt-team/guestfs-tools.git
    source-type: git
    source-tag: debian/1.46.1-4
    plugin: autotools
    override-pull: |
      sed -ie 's/^# deb-src/deb-src/' /etc/apt/sources.list; apt -y update
      mkdir _tmp && cd _tmp
      apt source guestfs-tools
      mv guestfs-tools-*/* ..
      cd ..
      rm -rf _tmp
    build-environment:
      - PYTHON: /usr/bin/python3
      - QEMU_CPU: "$(dpkg-architecture -qDEB_HOST_GNU_CPU | sed -r -e 's,i[456]86,i386,' -e 's,sparc.*,sparc64,' -e 's,powerpc(64.*)?,ppc64,' -e 's,arm.*,arm,')"
      - QEMU: /snap/$CRAFT_PROJECT_NAME/current/usr/bin/qemu-system-$QEMU_CPU
    override-build: |
      sed -ie 's/^# deb-src/deb-src/' /etc/apt/sources.list; apt -y update
      apt build-dep -y guestfs-tools
      patch -p1 < $CRAFT_PROJECT_DIR/patch/patch-libguestfs-dib-feature-modify-image.patch
      mkdir -p /snap/$CRAFT_PROJECT_NAME
      ln -sf $CRAFT_STAGE /snap/$CRAFT_PROJECT_NAME/current
      dpkg-source --before-build .
      autoreconf
      craftctl default
      rm -f /snap/$CRAFT_PROJECT_NAME/current
      rmdir /snap/$CRAFT_PROJECT_NAME
    autotools-configure-parameters:
      - --disable-silent-rules
      - --disable-gnulib-tests
      - --with-readline
      - --disable-haskell
      - --disable-java
      - --disable-golang
      - --disable-python
      - --disable-perl
      - --disable-php
      - --disable-gobject
      - --disable-lua
      - --disable-erlang
      - --disable-ruby
      - --without-libvirt
      - --prefix=/usr
    stage-packages:
      - libc6
