name: octavia-diskimage-retrofit
icon: src/icon.svg
version: script
version-script: bin/version
grade: stable
summary: tool for retrofitting cloud images for use as Octavia Amphora image.
description: |
  tool for retrofitting cloud images for use as Octavia Amphora image.
confinement: devmode
base: core18
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64
  - build-on: ppc64el

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
  /usr/share/qemu:
    bind: $SNAP/usr/share/qemu
  /usr/share/seabios:
    bind: $SNAP/usr/share/seabios
  /usr/lib/ipxe:
    bind: $SNAP/usr/lib/ipxe

environment:
  LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
  LIBGUESTFS_PATH: $SNAP/usr/local/lib/guestfs/appliance
  TMPDIR: $SNAP_COMMON/tmp
apps:
  octavia-diskimage-retrofit:
    command: bin/retrofit.sh
    plugs:
      - fuse-support
      - kvm
      - network-bind
parts:
  retrofit:
    plugin: dump
    source: src/retrofit
    organize:
      retrofit.sh: bin/retrofit.sh
  local-elements:
    plugin: dump
    source: src
    organize: 
      elements/*: usr/local/lib/elements/
  octavia-elements:
    plugin: dump
    source: https://opendev.org/openstack/octavia.git
    source-type: git
    source-branch: stable/victoria
    override-pull: |
      snapcraftctl pull
      patch  -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-octavia-elements-amphora-agent-ureadahead.patch
    organize:
      elements/*: usr/local/lib/elements/
  diskimage-builder:
    plugin: python
    source: https://opendev.org/openstack/diskimage-builder.git
    source-type: git
    source-branch: 2.25.0
    override-build: |
      find diskimage_builder/elements/ -type f -print0 | xargs -0 sed -i '1 s/^#\!.*python$/#\!\/usr\/bin\/env python3/'
      snapcraftctl build
  fuse:
    source: https://git.launchpad.net/ubuntu/+source/fuse
    source-type: git
    source-branch: ubuntu/bionic
    plugin: autotools
    override-build: |
      dpkg-source --before-build .
      autoreconf
      snapcraftctl build
    override-stage: |
      snapcraftctl stage
      chmod 0755 bin/fusermount
    filesets:
      exclude:
        - -dev
    stage:
      - $exclude
  libguestfs:
    after: [diskimage-builder,fuse]
    source: https://github.com/libguestfs/libguestfs.git
    source-type: git
    source-branch: v1.40.2
    plugin: autotools
    build-environment:
      - PYTHON: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/bin/python3
      - QEMU_CPU: "$(dpkg-architecture -qDEB_HOST_GNU_CPU | sed -r -e 's,i[456]86,i386,' -e 's,sparc.*,sparc64,' -e 's,powerpc(64.*)?,ppc64,' -e 's,arm.*,arm,')"
      - QEMU: /usr/bin/qemu-system-$QEMU_CPU
    override-build: |
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-libguestfs-autogen.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-libguestfs-m4-guestfs-qemu.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-libguestfs-po-Don-t-fail-installation-if-parts-of-translated-do.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-ocaml-lgnu.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-ocaml-examples-gnulib.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-libguestfs-dib-feature-modify-image.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-libguestfs-appliance-init-resolvconf.patch
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patch/patch-libguestfs-ppc64el-cap-htm.patch
      mkdir -p /snap/$SNAPCRAFT_PROJECT_NAME
      ln -sf $SNAPCRAFT_STAGE /snap/$SNAPCRAFT_PROJECT_NAME/current
      snapcraftctl build
      rm -f /snap/$SNAPCRAFT_PROJECT_NAME/current
      rmdir /snap/$SNAPCRAFT_PROJECT_NAME
    override-prime: |
      mkdir -p usr/local/lib/guestfs/appliance
      mkdir -p /snap/$SNAPCRAFT_PROJECT_NAME
      ln -sf $SNAPCRAFT_STAGE /snap/$SNAPCRAFT_PROJECT_NAME/current
      env -i LIBGUESTFS_PATH=$SNAPCRAFT_STAGE/lib/guestfs LD_LIBRARY_PATH=$SNAPCRAFT_STAGE/lib:$SNAPCRAFT_STAGE/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/lib:$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET PATH=$SNAPCRAFT_STAGE/usr/sbin:$SNAPCRAFT_STAGE/usr/bin:$SNAPCRAFT_STAGE/sbin:$SNAPCRAFT_STAGE/bin:/usr/sbin:/usr/bin:/sbin:/bin LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1 libguestfs-make-fixed-appliance $SNAPCRAFT_PRIME/usr/local/lib/guestfs/appliance
      rm -f /snap/$SNAPCRAFT_PROJECT_NAME/current
      rmdir /snap/$SNAPCRAFT_PROJECT_NAME
      chmod 0644 usr/local/lib/guestfs/appliance/kernel
      snapcraftctl prime
    configflags:
      - --disable-silent-rules
      - --disable-gnulib-tests
      - --with-readline
      - --disable-haskell
      - --disable-java
      - --disable-golang
      - --disable-python
      - --disable-perl
      - --disable-php
      - --disable-gobject
      - --disable-lua
      - --disable-erlang
      - --disable-ruby
      - --without-libvirt
    stage-packages:
      - libmagic1
      - uuid-runtime
      - libjansson4
      - libicu60
      - libxml2
      - ipxe-qemu-256k-compat-efi-roms
      - on amd64:
        - qemu-system-x86
      - on arm64:
        - qemu-system-arm
      - on armhf:
        - qemu-system-arm
      - on i386:
        - qemu-system-x86
      - on ppc64el:
        - qemu-system-ppc
      - on s390x:
        - qemu-system-s390x
      - qemu-utils
      - libslang2
    build-packages:
      - bison
      - flex
      - gperf
      - libaugeas-dev
      - gettext
      - libmagic-dev
      - libreadline-dev
      - libyajl-dev
      - ocaml-findlib
      - ocaml-nox
      - libgettext-ocaml-dev
      - python3-all-dev
      - libjansson-dev
      - libhivex-ocaml-dev
      - perl-doc
      - bsdmainutils
      - btrfs-tools
      - cryptsetup
      - dash
      - genisoimage
      - gfs2-utils
      - hfsplus
      - iproute2
      - iputils-ping
      - iputils-arping
      - iputils-tracepath
      - isc-dhcp-client
      - ldmtool
      - libaugeas0
      - libc-bin
      - libcap2
      - libhivex0
      - libjansson4
      - libpcre3
      - libsystemd0
      - libsystemd-dev
      - libtirpc1
      - libyara3
      - mtools
      - nilfs-tools
      - ntfs-3g
      - openssh-client
      - reiserfsprogs
      - sysvinit-utils
      - systemd
      - vim-tiny
      - xz-utils
      - uuid-runtime
      - acl
      - attr
      - bash
      - binutils
      - btrfs-progs
      - bzip2
      - coreutils
      - cpio
      - diffutils
      - dosfstools
      - e2fsprogs
      - f2fs-tools
      - file
      - findutils
      - gawk
      - gdisk
      - grep
      - gzip
      - jfsutils
      - kmod
      - less
      - libxml2
      - lsof
      - lsscsi
      - lvm2
      - lzop
      - mdadm
      - module-init-tools
      - parted
      - pciutils
      - procps
      - psmisc
      - rsync
      - scrub
      - sed
      - sleuthkit
      - squashfs-tools
      - strace
      - tar
      - udev
      - util-linux
      - xfsprogs
      - zerofree
      - qemu-utils
      - curl
      - kpartx
      - debootstrap
      - exfat-fuse
      - exfat-utils
      - dpkg-dev
      - supermin
      - ipxe-qemu-256k-compat-efi-roms
      - libslang2
      - on amd64:
        - linux-image-virtual
        - syslinux
        - extlinux
        - zfs-fuse
        - qemu-system-x86
      - on arm64:
        - linux-image-virtual
        - qemu-system-arm
      - on armhf:
        - linux-image-generic
        - qemu-system-arm
      - on i386:
        - linux-image-virtual
        - syslinux
        - extlinux
        - zfs-fuse
        - qemu-system-x86
      - on ppc64el:
        - linux-image-virtual
        - zfs-fuse
        - qemu-system-ppc
      - on s390x:
        - linux-image-virtual
        - qemu-system-s390x
