name: Build and Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the snap
        id: snapcraft
        uses: snapcore/action-build@v1
      - name: Install the snap
        run: |
          sudo snap install --dangerous --classic ${{ steps.snapcraft.outputs.snap }}
      - name: Get the Ubuntu Noble Image
        run: |
          sudo wget --continue -O /var/snap/octavia-diskimage-retrofit/common/tmp/noble.img \
              https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
      - name: Retrofitting noble image
        run: |
          cd /var/snap/octavia-diskimage-retrofit/common/tmp
          octavia-diskimage-retrofit -d noble.img noble-amphora.qcow2

      - name: Test if the image can be booted
        run: |
          set -x
          qemu-system-x86_64 \
              -m 2G \
              -drive file=/var/snap/octavia-diskimage-retrofit/common/tmp/noble-amphora.qcow2,format=qcow2 \
              -nographic \
              -serial mon:stdio,logfile=serial.log \
              -display none \
              -device virtio-net-pci,netdev=net0 \
              -netdev user,id=net0,hostfwd=tcp::2222-:22 \
              -accel kvm &

          timeout 300 bash -c 'until nc -z localhost 2222; do echo -n .; sleep 5; done'

          tail -n 5 serial.log
          grep "login:" serial.log

      - name: Upload built snap artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: ignore
      - name: Upload serial log artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serial.log
          path: serial.log
          if-no-files-found: ignore
